package com.Spring.AI_Customer_Support_Backend_System.Entities;

import com.Spring.AI_Customer_Support_Backend_System.Entities.Type.PriorityType;
import com.Spring.AI_Customer_Support_Backend_System.Entities.Type.CategoryType;
import com.Spring.AI_Customer_Support_Backend_System.Entities.Type.StatusType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table(
        name = "tickets",
        uniqueConstraints = @UniqueConstraint(
                name = "uk_conversation_ticket",
                columnNames = "conversation_id"
        ),
        indexes = {
                @Index(name="idx_ticket_status", columnList="status"),
                @Index(name="idx_ticket_priority", columnList="priority"),
                @Index(name="idx_ticket_category", columnList="category"),
                @Index(name="idx_ticket_assigned_to", columnList="assigned_to"),
                @Index(name="idx_ticket_created_by", columnList="created_by"),
                @Index(name="idx_ticket_created_at", columnList="created_at")
        }
)
public class Ticket {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;
    @Column(nullable = false)
    private String title;
    //Description can be long --- this prevents DB truncation issues ---
    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private StatusType status;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PriorityType priority;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private CategoryType category;

    @OneToOne
    @JoinColumn(name = "conversation_id", unique = true)
    private Conversation conversation;

    @ManyToOne
    @JoinColumn(name="created_by", nullable = false)
    private User createdBy;
    @ManyToOne
    @JoinColumn(name = "assigned_to") //Tickets can exists without any Agent
    private User assignedTo;



    @CreationTimestamp
    private LocalDateTime createdAt;
    @UpdateTimestamp
    private LocalDateTime updatedAt;


}
//Ticket has id, title, description, status(OPEN,IN PROGRESS or CLOSED), priority(LOW, MEDIUM or HIGH), category ( PAYMENT,TECHNICAL) etc
//It also has conversationId --- for tickets generated by AI through conversation
//createdBy --- USer
//assignedTO --- Agent
//
