package com.Spring.AI_Customer_Support_Backend_System.DTO;

import com.Spring.AI_Customer_Support_Backend_System.Entities.Type.CategoryType;
import com.Spring.AI_Customer_Support_Backend_System.Entities.Type.PriorityType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TicketAnalysisDTO implements Serializable {

    private String title;
    private PriorityType priority;
    private CategoryType category;
    private String reason;

    public static TicketAnalysisDTO fallback(String message) {
        return TicketAnalysisDTO.builder()
                .title(defaultTitle(message))
                .priority(PriorityType.MEDIUM)
                .category(CategoryType.GENERAL)
                .reason("Fallback analysis used because AI classification could not be parsed.")
                .build();
    }

    //If the AI fails then we give a defaultTitle to the ticket ---- from the fallback ---
    //The defaultTitle is determined here
    private static String defaultTitle(String message) {
        if (message == null || message.isBlank()) {
            return "Customer Support Issue";
        }
        //We normalise the string and allow only first 50 characters ---
        String normalized = message.replaceAll("\\s+", " ").trim();
        return normalized.length() <= 50 ? normalized : normalized.substring(0, 50);
    }
}
//It consists of all the ticket details generated by the AI ----
//If the AI fails then we provide fallback
